GET http://localhost:3002

###

POST http://localhost:3002/register
Content-Type: application/json

{
    "name" : "xohn",
    "email" : "y1109y@gmail.com",
    "password" : "cookies"
}

###

POST http://localhost:3002/signin
Content-Type: application/json

{
    "email" : "y1109y@gmail.com",
    "password" : "cookies"
}

###

PUT http://localhost:3002/image
Content-Type: application/json

{
    "id": "42"
}